- name: ' Konductor | Provision UPI Infra | validate-source-cluster-pre-backup.yml'
  hosts: localhost
  vars_files:
    - 'vars/vault.yml'
    - 'vars/oadp-migration.yml'
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "Retieve and validate Backup Source Cluster Info"
    ansible_name_module: " Post Cluster Installation | {{ module }}"

  pre_tasks:
    - name: '{{ ansible_name_module }} | validate required variables '
      block:
        - name: '{{ ansible_name_module }} | assert | the Source Cluster API URL is defined'
          ansible.builtin.assert:
            that:
              - backup_src_cluster_console_url is defined
              - backup_src_cluster_console_url != ''
            msg: "The Source cluster login URL is required for SA Token Retrieval"
        - name: '{{ ansible_name_module }} | assert | the Source Cluster API Token is defined'
          ansible.builtin.assert:
            that:
              - backup_src_cluster_token is defined
              - backup_src_cluster_token != ''
            msg: "The Source cluster login Token is required for SA Token Retrieval"
        - name: '{{ ansible_name_module }} | set_fact | namespacelist '
          ansible.builtin.set_fact:
            backup_src_cluster_console_port: '6443'
          when:
            - not backup_src_cluster_console_port is defined or backup_src_cluster_console_port == ''

  tasks:
    - name: '{{ ansible_name_module }} | import_tasks | Import Backup Source Cluster Info retrieval additional tasks'
      ansible.builtin.import_tasks: tasks/retrieve-backup-source-cluster-info.yml
      vars:
        skip_prereq_validation: 'true'
        apply_ns_exlusion: 'true'
