---
- name: '{{ ansible_name_module }} | Authenticate with the API'
  ansible.builtin.command: >
    {{ openshift_cli }} login \
      --token {{ backup_src_cluster_token }} \
      --insecure-skip-tls-verify=true {{ backup_src_cluster_console_url }}:{{ backup_src_cluster_console_port | d('6443', true) }}
  when:
    - not skip_api_login_logout is defined or not skip_api_login_logout | bool

- name: '{{ ansible_name_module }} | Retrieve and Print Backup Info'
  when:
    - remove_failed_backup is defined 
    - remove_failed_backup | bool 
  block:
    - name: '{{ ansible_name_module }} | Failed Backups'
      ansible.builtin.shell: >
        {{ openshift_cli }} get backup.velero.io --all-namespaces -o json | jq '[.items[] | select(.status.phase == "PartiallyFailed") | {"name": .metadata.name, "namespace": .metadata.namespace, "uid": .metadata.uid}]' | jq '.[] | [.name, .namespace, .uid] | join(" , ")' | jq -r 
      register: failed_backup_list_retrieved 

    - name: '{{ ansible_name_module }} | template | Render DeleteBackupRequest CR'
      ansible.builtin.template:
        src: "templates/oadp-delete-backup-request.yaml.j2"
        dest: "{{ staging_dir | d('/tmp', true) }}/{{ backup_name }}-oadp-delete-backup-request.yaml"
        force: yes
      loop: "{{ failed_backup_list_retrieved.stdout_lines }}"
      vars:
        backup_name: '{{ item.split(" , ")[0] }}'
        oadp_backup_ns: '{{ item.split(" , ")[1] }}' 
        backup_uid: '{{ item.split(" , ")[2] }}'
      when:
        - failed_backup_list_retrieved is defined
        - failed_backup_list_retrieved.stdout_lines is defined
        - failed_backup_list_retrieved.stdout_lines | length > 0 
        - item is defined
        - item != ''
      register: oadp_dbr_manifest_copied

    - name: '{{ ansible_name_module }} | ansible.builtin.debug | Print output rendered manifests'
      ansible.builtin.debug:
        var: item
        verbosity: 2
      loop: "{{ oadp_dbr_manifest_copied.results }}"
      when:
        - oadp_dbr_manifest_copied is defined
        - oadp_dbr_manifest_copied.results is defined
        - oadp_dbr_manifest_copied.results | length > 0 
        - item.dest is defined
        - item.state is defined
        - "'file' in  item.state"

    - name: '{{ ansible_name_module }} | ansible.builtin.command:{{ openshift_cli }} apply | create DeleteBackupRequest CR'
      ansible.builtin.command: >
        {{ openshift_cli }} apply -f {{ item.dest }}
      loop: "{{ oadp_dbr_manifest_copied.results }}"
      when:
        - oadp_dbr_manifest_copied is defined
        - oadp_dbr_manifest_copied.results is defined
        - oadp_dbr_manifest_copied.results | length > 0 
        - item.dest is defined
        - item.state is defined
        - "'file' in  item.state"
      register: oadp_dbr_manifest_applied

    #- name: '{{ ansible_name_module }} | Remove failed backup CR'
    #  ansible.builtin.command: >
    #    {{ openshift_cli }} delete backup.velero.io {{ item }}  
    #  loop: "{{ failed_backup_list_retrieved.stdout_lines }}"
    #  when:
    #    - failed_backup_list_retrieved is defined
    #    - failed_backup_list_retrieved.rc is defined
    #    - failed_backup_list_retrieved.rc == 0 
    #    - failed_backup_list_retrieved.stdout_lines is defined
    #    - failed_backup_list_retrieved.stdout_lines | length > 0
    #  register: failed_backup_removed 

- name: '{{ ansible_name_module }} | Logout of the current source cluster to kill any session'
  ansible.builtin.command: >
    {{ openshift_cli }} logout \
      --insecure-skip-tls-verify=true -s {{ backup_src_cluster_console_url }}:{{ backup_src_cluster_console_port | d('6443', true) }}
  when:
    - not skip_api_login_logout is defined or not skip_api_login_logout | bool

