---
- name: '{{ ansible_name_module }} | Configure S3 Storage Repo for MTC '
  ansible.builtin.include_tasks: tasks/configure-mtc-replication-repo.yml
  when:
    - add_replication_repo is defined 
    - add_replication_repo | bool 
    - mig_cntl_storagerepo_name is defined
    - mig_cntl_storagerepo_name != '' 

- name: '{{ ansible_name_module }} | Add Source cluster to MTC '
  ansible.builtin.include_tasks: tasks/configure-mtc-mig-cluster.yml 
  when:
    - add_mig_cluster is defined 
    - add_mig_cluster | bool 

- name: '{{ ansible_name_module }} | Add Migration Plan Resources to MTC '
  when:
    - add_migration_plan is defined 
    - add_migration_plan | bool 
  block:
    - name: '{{ ansible_name_module }} | assert | the Mig Plan destination host Name is defined'
      ansible.builtin.assert:
        that:
          - mig_cntl_desthost is defined
          - mig_cntl_desthost != '' 
        msg: "The MIG Plan destination host name is required to add the Mig Plan manifests"

    - name: '{{ ansible_name_module }} | assert | the Mig Plan Name is defined'
      ansible.builtin.assert:
        that:
          - default_mig_cntl_migplan_name is defined
          - default_mig_cntl_migplan_name != '' 
        msg: "The MIG Plan name is required to add the Mig Plan manifests"

    - name: '{{ ansible_name_module }} | assert | the List of Namespace to migrate is defined'
      ansible.builtin.assert:
        that:
          - namespace_list is defined
          - namespace_list != ''
          - namespace_list | length > 0 
        msg: "The List of Namespaces to migrate is required to add the Mig Plan manifests"

    - name: '{{ ansible_name_module }} | set_fact | set updated_namespaces_to_backup'
      ansible.builtin.set_fact:
        updated_namespaces_to_backup: '{{ namespace_list }}'

    ### Process Mig plan by namespace
    - name: '{{ ansible_name_module }} | Add Migration Plan Resources to MTC  '
      ansible.builtin.include_tasks:  tasks/process-mtc-mig-plan-cr.yml 
       loop: "{{ updated_namespaces_to_backup }}"
      loop_control:
        index_var: key_cnt
      vars:
        mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}-{{ item }}"
        namespace_list: '{{ [item] }}'
      when:
        - process_backup_per_namespace is defined
        - process_backup_per_namespace | bool
      register: all_backup_processed

    ### Process Mig plan for all namespaces
    - name: '{{ ansible_name_module }} | Add Migration Plan Resources to MTC  '
      ansible.builtin.include_tasks:  tasks/process-mtc-mig-plan-cr.yml 
      vars:
        mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}"
        namespace_list: '{{ updated_namespaces_to_backup }}'
      when:
        - not process_backup_per_namespace is defined or not process_backup_per_namespace | bool
      register: backup_bundle_processed

- name: '{{ ansible_name_module }} | Perform Migration in MTC '
  when:
    - perform_migration is defined 
    - perform_migration | bool 
  block:
    ### Process Migration by namespace
    - name: '{{ ansible_name_module }} | Add MigMigration Resources to MTC '
      ansible.builtin.include_tasks:  tasks/process-mtc-migration-cr.yml 
       loop: "{{ updated_namespaces_to_backup }}"
      loop_control:
        index_var: key_cnt
      vars:
        mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}-{{ item }}"
        mig_cntl_migration_name: "{{ default_mig_cntl_migplan_name }}-{{ item }}"
      when:
        - process_backup_per_namespace is defined
        - process_backup_per_namespace | bool
      register: all_backup_processed

    ### Process Migration for all namespaces
    - name: '{{ ansible_name_module }} | Add MigMigration Resources to MTC '
      ansible.builtin.include_tasks: tasks/process-mtc-migration-cr.yml 
      vars:
        mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}"
        mig_cntl_migration_name: "{{ default_mig_cntl_migplan_name }}"
      when:
        - not process_backup_per_namespace is defined or not process_backup_per_namespace | bool
      register: backup_bundle_processed

### Process Mig plan for namespaces with over the limit pvcs
- name: '{{ ansible_name_module }} | Process MTC Migration for namespace with pvc over limit  '
  ansible.builtin.include_tasks: tasks/process-mtc-crs-for-namespaces-with-pvcs-overlimit-from-source-cluster.yml 
  when:
    - process_namespaces_with_over_limit is defined
    - process_namespaces_with_over_limit | bool 

