---
- name: '{{ ansible_name_module }} | set_fact | manifest_backup_staging_dir '
  ansible.builtin.set_fact:
    manifest_backup_staging_dir: "{{ staging_dir | d('/tmp', true) }}/{{ backup_name }}/manifests" 
  when:
    - not manifest_backup_staging_dir is defined or not manifest_backup_staging_dir != ''

- name: '{{ ansible_name_module }} | set_fact | roles_manifest_backup_staging_dir '
  ansible.builtin.set_fact:
    roles_manifest_backup_staging_dir: "{{ staging_dir | d('/tmp', true) }}/{{ backup_name }}/manifests/roles" 
  when:
    - not roles_manifest_backup_staging_dir is defined or not roles_manifest_backup_staging_dir != ''

- name: '{{ ansible_name_module }} | ansible.builtin.file | Ensure the manifests download staging dir exist '
  ansible.builtin.file:
    path: "{{ manifest_backup_staging_dir }}"
    state: directory
    mode: 0777

- name: '{{ ansible_name_module }} | shell:{{ openshift_cli }} get | download all manifestss in cluster '
  ansible.builtin.shell: >
    {{ openshift_cli }} get dc,deployments,statefulsets,daemonsets,cronjobs,secrets,configmaps,services,routes,ingress,networkpolicies,buildconfigs,imagestreams -n {{ item }}  -o yaml --show-managed-fields=false >  {{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ item }}-manifest.yaml
  loop: "{{ raw_manifests_namespace_list }}"
  ignore_errors: true
  register: manifests_downloaded

- name: '{{ ansible_name_module }} | shell:{{ openshift_cli }} get | download all bound pvcs in cluster '
  ansible.builtin.shell: >
    {{ openshift_cli }} get roles,rolebindings,serviceaccounts,users,groups -n {{ item }}  -o yaml --show-managed-fields=false >  {{roles_manifest_backup_staging_dir }}/{{ backup_name }}-{{ item }}-usermgt.yaml
  loop: "{{ raw_manifests_namespace_list }}"
  ignore_errors: true
  register: usermgt_manifests_downloaded

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 1 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "creationTimestamp:"
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 2 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "resourceVersion: "
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 3 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "uid: "
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 4 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "lastScheduleTime: "
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 5 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "lastSuccessfulTime: "
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 6 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "status:"
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 7 of 7'
  ansible.builtin.lineinfile:
    path: "{{ manifest_file_path }}"
    regexp: "generation: "
    state: absent
  loop: "{{ manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    manifest_file_path: "{{ manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-manifest.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 1 of 3'
  ansible.builtin.lineinfile:
    path: "{{ usermgt_manifest_file_path }}"
    regexp: "creationTimestamp:"
    state: absent
  loop: "{{ usermgt_manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    usermgt_manifest_file_path: "{{ roles_manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-usermgt.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 2 of 3'
  ansible.builtin.lineinfile:
    path: "{{ usermgt_manifest_file_path }}"
    regexp: "resourceVersion: "
    state: absent
  loop: "{{ usermgt_manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    usermgt_manifest_file_path: "{{ roles_manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-usermgt.yaml"

- name:  '{{ ansible_name_module }} | Remove unecessary metadata from exported file 3 of 3'
  ansible.builtin.lineinfile:
    path: "{{ usermgt_manifest_file_path }}"
    regexp: "uid: "
    state: absent
  loop: "{{ usermgt_manifests_downloaded.results }}"
  loop_control:
    index_var: key_cnt
  when:
    - item is defined
    - item.rc is defined
    - item.rc == 0 
  vars:
    usermgt_manifest_file_path: "{{ roles_manifest_backup_staging_dir }}/{{ backup_name }}-{{ raw_manifests_namespace_list[key_cnt] }}-usermgt.yaml"

- name: '{{ ansible_name_module }} | upload raw manifests to S3 bucket '
  block:
    - name: '{{ ansible_name_module }} | command:which | Check if aws cli is installed'
      ansible.builtin.shell: >
        which aws 
      ignore_errors: yes
      register: aws_binary

    - name: '{{ ansible_name_module }} | assert | the AWS CLI binary is defined'
      ansible.builtin.assert:
        that:
          - aws_binary is defined
          - aws_binary.rc is defined
          - aws_binary.rc == 0 
          - aws_binary.stdout is defined
          - aws_binary.stdout != '' 
        msg: "The AWS CLI binary is required to upload the raw manifest to the S3 bucket "

    - name: '{{ ansible_name_module }} | set_fact | aws_cli '
      ansible.builtin.set_fact:
        aws_cli: '{{ aws_binary.stdout }}'

    - name: '{{ ansible_name_module }} | command:shell | copy raw manifest directory to S3 bucket'
      ansible.builtin.shell: >
        {{ aws_cli }} s3 --region {{ oadp_bucket_region }} sync {{ manifest_backup_staging_dir }}/ \
         s3://{{ oadp_s3_bucket }}/{{ oadp_backup_prefix }}/raw-manifests \
         --endpoint-url https://{{ oadp_s3url }} --no-verify-ssl
      environment:
        AWS_ACCESS_KEY_ID: "{{ oadp_bucket_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ oadp_bucket_access_secret }}"
      register: manifests_uploaded
