---
- name: '{{ ansible_name_module }} | Authenticate with the API'
  ansible.builtin.command: >
    {{ openshift_cli }} login \
      --token {{ src_mtc_cluster_token }} \
      --insecure-skip-tls-verify=true {{ src_mtc_cluster_console_url }}:{{ src_mtc_cluster_console_port | d('6443', true) }}
  when:
    - not skip_api_login_logout is defined or not skip_api_login_logout | bool

- name: '{{ ansible_name_module }} | shell:{{ openshift_cli }} get | all bound pvcs in cluster '
  ansible.builtin.shell: >
    {{ openshift_cli }} get pvc -A  -o json | jq -r '.items[] | select([.status.phase] | inside(["Bound"]))' | jq -s '. | group_by(.metadata.namespace) | map({namespace: .[0].metadata.namespace, count: length} | select(.count >= 26))' 
  register: namespaces_with_bound_pvcs_over_limit_with_count

- name: '{{ ansible_name_module }} | ansible.builtin.debug | Print first half of bound pvcs namespaces output '
  ansible.builtin.debug:
    var: item 
    verbosity: 2
  loop: "{{ namespaces_with_bound_pvcs_over_limit_with_count.stdout_lines }}"
  when:
    - namespaces_with_bound_pvcs_over_limit_with_count is defined
    - namespaces_with_bound_pvcs_over_limit_with_count.stdout_lines is defined
    - namespaces_with_bound_pvcs_over_limit_with_count.stdout_lines | length > 0 

- name: '{{ ansible_name_module }} | set_fact | set namespaces_with_bound_pvcs_over_limit_with_count in array format'
  ansible.builtin.set_fact:
    namespaces_with_bound_pvcs_over_limit_list: '{{ namespaces_with_bound_pvcs_over_limit_with_count.stdout | from_json | list }}'
  when:
    - namespaces_with_bound_pvcs_over_limit_with_count is defined
    - namespaces_with_bound_pvcs_over_limit_with_count.stdout_lines is defined
    - namespaces_with_bound_pvcs_over_limit_with_count.stdout_lines | length > 0 

- name: '{{ ansible_name_module }} | ansible.builtin.debug | Print first half of bound pvcs namespaces output '
  ansible.builtin.debug:
    var: namespaces_with_bound_pvcs_over_limit_list 
  when:
    - namespaces_with_bound_pvcs_over_limit_list is defined
    - namespaces_with_bound_pvcs_over_limit_list | length > 0

- name: '{{ ansible_name_module }} | ansible.builtin.debug | Print first half of bound pvcs namespaces output '
  ansible.builtin.debug:
    var: item
  loop: "{{ namespaces_with_bound_pvcs_over_limit_list }}"
  when:
    - namespaces_with_bound_pvcs_over_limit_list is defined
    - namespaces_with_bound_pvcs_over_limit_list | length > 0

- name: '{{ ansible_name_module }} | set_fact | create and empty merged_over_limit_namespace_with_pvc_list '
  ansible.builtin.set_fact:
    merged_over_limit_namespace_with_pvc_list: [] 

- name: '{{ ansible_name_module }} | process namespaces with overlimit pvc count'
  ansible.builtin.include_tasks: tasks/process-namespace-with-overlimit-pvc-count.yml
  loop: "{{ namespaces_with_bound_pvcs_over_limit_list }}"
  loop_control:
    loop_var: current_ns
  when:
    - namespaces_with_bound_pvcs_over_limit_list is defined
    - namespaces_with_bound_pvcs_over_limit_list | length > 0

- name: '{{ ansible_name_module }} | ansible.builtin.debug | Print merged_over_limit_namespace_with_pvc_list output '
  ansible.builtin.debug:
    msg: "The list of over_limit_namespaces_with_pvc_list is : {{ merged_over_limit_namespace_with_pvc_list }}"
    verbosity: 2
  when:
    - merged_over_limit_namespace_with_pvc_list is defined
    - merged_over_limit_namespace_with_pvc_list | length > 0 

- name: '{{ ansible_name_module }} | ansible.builtin.debug | Print merged_over_limit_namespace_with_pvc_list output '
  ansible.builtin.debug:
    var: item
    verbosity: 2
  loop: "{{ merged_over_limit_namespace_with_pvc_list }}"
  when:
    - merged_over_limit_namespace_with_pvc_list is defined
    - merged_over_limit_namespace_with_pvc_list | length > 0 

### Process Mig plan by namespace
- name: '{{ ansible_name_module }} | Add Migration Plan Resources to MTC  '
  ansible.builtin.include_tasks:  tasks/process-mtc-mig-plan-cr.yml
  loop: "{{ merged_over_limit_namespace_with_pvc_list }}"
  vars:
    mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}-{{ item.name }}"
    namespace_list: '{{ [item.pvcs[0].metadata.namespace] }}'
    include_pvs: "true"
    ns_with_pvc_list: "{{ item.pvcs }}"
  when:
    - merged_over_limit_namespace_with_pvc_list is defined
    - merged_over_limit_namespace_with_pvc_list | length > 0 
  register: all_backup_processed

 ### Process Migration by namespace
- name: '{{ ansible_name_module }} | Add MigMigration Resources to MTC '
  ansible.builtin.include_tasks:  tasks/process-mtc-migration-cr.yml
  loop: "{{ merged_over_limit_namespace_with_pvc_list }}"
  vars:
    mig_cntl_migplan_name: "{{ default_mig_cntl_migplan_name }}-{{ item.name }}"
    mig_cntl_migration_name: "{{ default_mig_cntl_migplan_name }}-{{ item.name }}"
  when:
    - merged_over_limit_namespace_with_pvc_list is defined
    - merged_over_limit_namespace_with_pvc_list | length > 0 
  register: all_backup_processed

- name: '{{ ansible_name_module }} | Logout of the current source cluster to kill any session'
  ansible.builtin.command: >
    {{ openshift_cli }} logout \
      --insecure-skip-tls-verify=true -s {{ src_mtc_cluster_console_url }}:{{ src_mtc_cluster_console_port | d('6443', true) }}
  when:
    - not skip_api_login_logout is defined or not skip_api_login_logout | bool

