---
- name: '{{ ansible_name_module }} | import_tasks | Import additional restore schedule CR processing tasks'
  ansible.builtin.include_tasks: process-restore-schedule.yml 
  when:
    - add_oadp_schedule is defined
    - add_oadp_schedule | bool 
  register: oadp_schedule_cr_copied

- name: '{{ ansible_name_module }} | import_tasks | Import additional restore CR processing tasks'
  ansible.builtin.include_tasks: process-restore-cr.yml 
  register: oadp_restore_cr_copied

