apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-blue-green
  namespace: haproxy-system
  labels:
    app: haproxy-blue-green
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy-blue-green
  template:
    metadata:
      labels:
        app: haproxy-blue-green
        version: v1.0.0
    spec:
      containers:
      - name: haproxy
        image: docker.io/haproxy:2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 8404
          name: stats
          protocol: TCP
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy
          readOnly: true
        - name: haproxy-ssl
          mountPath: /etc/ssl
          readOnly: true
        livenessProbe:
          httpGet:
            path: /stats
            port: 8404
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46Y2hhbmdlbWU="  # admin:changeme base64 encoded
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /stats
            port: 8404
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46Y2hhbmdlbWU="  # admin:changeme base64 encoded
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
      - name: haproxy-ssl
        secret:
          secretName: haproxy-ssl
          optional: true
      securityContext:
        fsGroup: 1000
      restartPolicy: Always 