apiVersion: v1
kind: Service
metadata:
  name: haproxy-blue-green
  namespace: haproxy-system
  labels:
    app: haproxy-blue-green
    service: load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 8404
    targetPort: 8404
    protocol: TCP
    name: stats
  selector:
    app: haproxy-blue-green
  sessionAffinity: None 